config/routes.rb
Rails.application.routes.draw do
  get 'bitcoins', to: 'bitcoins#index'
  get 'bitcoins/convert'
  root 'exchanges#index'
  get 'convert', to: 'exchanges#convert'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bitcoins_controller.rb
class BitcoinsController < ApplicationController
  def index
  end

  def convert
    value = BitcoinService.new(params[:source_currency], params[:target_currency], params[:amount]).call
    render json: { value: value }
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def index
  end

  def convert
    value = ExchangeService.new(params[:source_currency], params[:target_currency], params[:amount]).call
    render json: { value: value }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitcoins_helper.rb
module BitcoinsHelper
  def available_currencies
    [
      "AUD", "BRL", "BTC", "CAD", "CHF", "CLP", "CNY", "DKK", "EUR", "GBP",
      "HKD", "INR", "ISK", "JPY", "KRW", "NZD", "PLN", "RUB", "SEK", "SGD",
      "THB", "TRY", "TWD", "USD"
    ]
  end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
  def currency_list
    [
      'AUD', 'BGN', 'BRL', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP',
      'HKD', 'HRK', 'HUF', 'IDR', 'ILS', 'INR', 'JPY', 'KRW', 'MXN',
      'MYR', 'NOK', 'NZP', 'PHP', 'PLN', 'RON', 'RUB', 'SEK', 'SGD',
      'THB', 'TRY', 'USD', 'ZAR'
    ]
  end
end

app/views/bitcoins/_bitcoin_box.html.erb
<div class="exchange_box col-sm-12">
  <div class="card">
    <div class="card-header text-center">
      Realize uma conversão
    </div>

    <div class="card-block">
      <%= form_with url: '/bitcoins/convert', method: :get, id: 'form' do |f| %>
        <div class="local-currency">
          <div class="form-group">
            <p class="title">
              Sua moeda &nbsp;
              <button type="button" class="btn data-transfer" click="changeSourceCurrency()">
                <%= image_tag('data-transfer.png') %>
              </button>
            </p>
            <%= f.select 'source_currency', options_for_select(available_currencies, 'BRL'), {}, { class: 'form-control', id: 'source_currency' } %>
          </div>

          <div class="form-group">
            <%= f.number_field 'amount', id: 'amount', class: 'form-control', placeholder: 'Quantidade ($10)', step: 'any', required: true %>
          </div>
        </div>

        <div class="destination_currency">
          <div class="form-group">
            <p class="title">
              Moeda destino &nbsp;
              <button type="button" class="btn data-transfer" click="changeSourceCurrency()">
                <%= image_tag('data-transfer.png') %>
              </button>
            </p>
            <%= f.select :target_currency, options_for_select(available_currencies, 'BTC'), {}, { class: 'form-control', id: 'target_currency' } %>
          </div>

          <div class="form-group">
              <input type="text" id="result" name="result" class="form-control" placeholder="Resultado" readonly>
          </div>
        </div>
      <% end %>

      <div class="row d-flex">
        <%= link_to 'Converter moedas', root_path, class: 'ml-auto btn btn-link' %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  const source_currency = document.getElementById('source_currency');
  const target_currency = document.getElementById('target_currency');
  const available_currencies = Array.from(source_currency.children);
  const btcIndex = available_currencies.findIndex((i) => i.value === 'BTC');
  source_currency.addEventListener('change', function(ev) {
    changeSourceCurrency();
  });
  const changeSourceCurrency = () => {
    if (source_currency.value === 'BTC') {
      for (let i = 0, l = available_currencies.length; i < l; i++) {
        target_currency.children[i].disabled = false;
      }
      target_currency.children[btcIndex].disabled = true;
      if (btcIndex === 0) {
        target_currency.options.selectedIndex = 1;
      } else {
        target_currency.options.selectedIndex = 0;
      }
    } else {
      for (let i = 0, l = available_currencies.length; i < l; i++) {
        target_currency.children[i].disabled = true;
      }
      target_currency.children[btcIndex].disabled = false;
      target_currency.options.selectedIndex = btcIndex;
    }
  }
  changeSourceCurrency();
</script>

app/views/bitcoins/index.html.erb
<div class="container">
  <div class="row main">
    <div class="col-lg-3 offset-lg-1 col-md-10 offset-md-1 box">
      <div class="row">
        <div class="col-md-8 offset-md-2 text-sm-center">
          <%= image_tag 'logo-desafio.png', class: 'img-fluid' %>
        </div>
      </div>

      <div class="row">
        <%= render 'bitcoin_box' %>
      </div>
    </div>

    <div class="col-lg-7 offset-lg-1 hidden-sm-down title-box">
      <div class="row">
        <h2 class="subtitle">Converta sua moeda para bitcoin e vice-versa.</h2>
      </div>

      <div class="row">
        <h2 class="subtitle">É fácil, experimente agora mesmo!</h2>
      </div>
    </div>
  </div>
</div>

app/views/exchanges/_exchange_box.html.erb
<div class="box col-sm-12">
  <div class="card">
    <div class="card-header text-center">
      Realize uma conversão
    </div>

    <div class="card-block">
      <%= form_with url: '/convert', method: :get, id: 'form' do |f| %>
        <div class="local-currency">
          <div class="form-group">
            <p class="title">
              Sua moeda &nbsp;
              <button type="button" class="btn data-transfer">
                <%= image_tag('data-transfer.png') %>
              </button>
            </p>
            <%= f.select 'source_currency', options_for_select(currency_list, 'BRL'), {}, { class: 'form-control', id: 'source_currency' } %>
          </div>

          <div class="form-group">
            <%= f.number_field 'amount', id: 'amount', class: 'form-control', placeholder: 'Quantidade ($10)', step: 'any', required: true %>
          </div>
        </div>

        <div class="destination_currency">
          <div class="form-group">
            <p class="title">
              Moeda destino &nbsp;
              <button type="button" class="btn data-transfer">
                <%= image_tag('data-transfer.png') %>
              </button>
            </p>
            <%= f.select 'target_currency', options_for_select(currency_list, 'EUR'), {}, { class: 'form-control', id: 'target_currency' } %>
          </div>

          <div class="form-group">
              <input type="text" id="result" name="result" class="form-control" placeholder="Resultado" readonly>
          </div>
        </div>
      <% end %>

      <div class="row d-flex">
        <%= link_to 'Converter bitcoins', bitcoins_path, class: 'ml-auto btn btn-link' %>
      </div>
    </div>
  </div>
</div>

app/views/exchanges/index.html.erb
<div class="container">
  <div class="row main">
    <div class="col-lg-3 offset-lg-1 col-md-10 offset-md-1 exchange_box">
      <div class="row">
        <div class="col-md-8 offset-md-2 text-sm-center">
          <%= image_tag 'logo-desafio.png', class: 'img-fluid' %>
        </div>
      </div>

      <div class="row">
        <%= render 'exchange_box' %>
      </div>
    </div>

    <div class="col-lg-7 offset-lg-1 hidden-sm-down title-box">
      <div class="row">
        <h2 class="subtitle">Converta sua moeda para qualquer outra.</h2>
      </div>

      <div class="row">
        <h2 class="subtitle">É fácil, experimente agora mesmo!</h2>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneBitExchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon-desafio.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>